export const REALTIME_EVENTS = Object.freeze({
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_ITEM_CHANGED: "ORDER_ITEM_CHANGED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
  TABLE_STATUS_CHANGED: "TABLE_STATUS_CHANGED",
  KITCHEN_ORDER_UPDATED: "KITCHEN_ORDER_UPDATED",
  EMPLOYEE_STATUS_CHANGED: "EMPLOYEE_STATUS_CHANGED",
  RESERVATION_UPDATED: "RESERVATION_UPDATED",
  COURIER_STATUS_CHANGED: "COURIER_STATUS_CHANGED",
  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
  MENU_UPDATED: "MENU_UPDATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  PATH_CHANGED: "PATH_CHANGED",
});

export const KITCHEN_STATUSES = new Set(["confirmed", "cooking", "ready"]);
