// security/sanitize.js — ID validation shared by every router that
// interpolates a client-supplied value into a Firebase Realtime Database
// path (e.g. `restaurants/${restId}/orders/${orderId}`). RTDB paths are
// segment-joined by "/", so an unvalidated restId/orderId containing "/"
// lets a request silently address a DIFFERENT path than the one the
// permission check (requirePermission/resolveRequestPermissions) actually
// authorized against — e.g. restId="A/../B" or restId="A/orders/secret"
// would resolve permissions for "A" but read/write somewhere else entirely.
// This is additive validation only: every legitimate restId/orderId/userId
// already generated by this app (Firebase push() keys, `${role}_${Date.now()}`
// staff ids, restaurant ids created via the existing admin flow) matches
// SAFE_ID_RE, so this never rejects real traffic — only malformed/malicious
// input that could never have been a valid record in the first place.
const SAFE_ID_RE = /^[A-Za-z0-9_-]{1,128}$/;

/** True if `value` is a safe single path segment (no "/", ".", "#", "$", "[", "]", no empty string). */
export function isSafeId(value) {
  return typeof value === "string" && SAFE_ID_RE.test(value);
}

/**
 * Express middleware: 400s the request before any handler/permission check
 * runs if restId (as resolved by the route's own getRestId helper) isn't a
 * safe single path segment. Mount this BEFORE requirePermission() on any
 * route so a spoofed restId can never reach the DB layer.
 */
export function requireSafeRestId(getRestId) {
  return function (req, res, next) {
    const restId = getRestId(req);
    if (restId != null && !isSafeId(String(restId))) {
      return res.status(400).json({ error: "Invalid restId" });
    }
    next();
  };
}

/** Same idea for a route param (e.g. :id, :orderId, :courierId). */
export function requireSafeParam(paramName) {
  return function (req, res, next) {
    const value = req.params[paramName];
    if (value != null && !isSafeId(String(value))) {
      return res.status(400).json({ error: `Invalid ${paramName}` });
    }
    next();
  };
}

/** Non-middleware helper for ad-hoc checks inside handlers (e.g. body fields). */
export function assertSafeId(value, label = "id") {
  if (!isSafeId(String(value ?? ""))) {
    const err = new Error(`Invalid ${label}`);
    err.statusCode = 400;
    throw err;
  }
}
